
CREATE TABLE ADDRESS (
    ID INT PRIMARY KEY,
	COUNTRY VARCHAR(100),
	STATE VARCHAR(100),
    ZIP VARCHAR(20),
    CITY VARCHAR(100),
    STREET VARCHAR(100),
    STREET_NR VARCHAR(20)
);

CREATE TABLE CUSTOMER (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100),
	IS_VIP INT DEFAULT 0,
    ADDRESS INT,
    FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ID)
);

CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100),
	HIRE_DATE DATE,
	JOB VARCHAR(100),
	WORKLOAD NUMERIC(10,2),
	SALARY INT,
    ADDRESS INT,
    REPORTS INT,
    FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ID),
    FOREIGN KEY (REPORTS) REFERENCES EMPLOYEE(ID),
	CHECK (WORKLOAD BETWEEN 0.0 AND 1.0)
);

CREATE TABLE SHOP (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    ADDRESS INT,
	MANAGER INT,
    FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ID),
	FOREIGN KEY (MANAGER) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE SHOP_EMPLOYEE_WORKS (
    SHOP INT NOT NULL,
	EMPLOYEE INT NOT NULL,
	UNIQUE(SHOP, EMPLOYEE)
);

CREATE TABLE BIKE_TYPE (
    ID INT PRIMARY KEY,
	TYPE_NAME VARCHAR(20),
	TYPE_DESCRIPTION VARCHAR(100)
);

CREATE TABLE BIKE (
    ID INT PRIMARY KEY,
    MODELL VARCHAR(100),
	FRAME_SIZE VARCHAR(20),
	WHEEL_SIZE VARCHAR(20),
	BIKE_TYPE INT,
	EBIKE INT,
    SHOP INT,
	FOREIGN KEY (BIKE_TYPE) REFERENCES BIKE_TYPE(ID),
    FOREIGN KEY (SHOP) REFERENCES SHOP(ID)
);

CREATE TABLE RENTAL (
    ID INT PRIMARY KEY,
    CUSTOMER INT,
    BIKE INT,
    RENTAL_DATE DATE,
    RETURN_DATE DATE,
	RESPONSIBLE INT,
    FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID),
    FOREIGN KEY (BIKE) REFERENCES BIKE(ID),
	FOREIGN KEY (RESPONSIBLE) REFERENCES EMPLOYEE(ID)
);


CREATE TABLE DAMAGE (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(100),
    RENTAL INT,
    DAMAGE_DATE DATE,
	STATUS INT,
	RESPONSIBLE INT,
	REPAIR_DATE DATE,
    REMARKS VARCHAR(100),
    FOREIGN KEY (RENTAL) REFERENCES RENTAL(ID),
	FOREIGN KEY (RESPONSIBLE) REFERENCES EMPLOYEE(ID)
);
