CREATE TABLE EMP (
   ID INT PRIMARY KEY,
   NAME VARCHAR(100),
   SHOP INT,
   HIRE_DATE DATE,
   JOB VARCHAR(100),
   WORKLOAD NUMERIC(10, 2),
   SALARY INT,
   ADDRESS INT,
   REPORTS_TO INT,
   FOREIGN KEY (REPORTS_TO) REFERENCES EMP(ID),
   CHECK (WORKLOAD BETWEEN 0.0 AND 1.0)
);

CREATE TABLE SHOP (
   ID INT PRIMARY KEY,
   NAME VARCHAR(100),
   ADDRESS INT,
   MANAGER INT
);

ALTER TABLE SHOP ADD CONSTRAINT FK_SHOP_MANAGER FOREIGN KEY (MANAGER) REFERENCES EMP(ID);
ALTER TABLE EMP ADD CONSTRAINT FK_EMP_SHOP FOREIGN KEY (SHOP) REFERENCES SHOP(ID);
