CREATE TABLE EMP (
   ID INT PRIMARY KEY,
   NAME VARCHAR(100),
   SHOP INT,
   HIRE_DATE DATE,
   JOB VARCHAR(100),
   WORKLOAD NUMERIC(10, 2),
   SALARY INT,
   ADDRESS INT,
   REPORTS_TO INT,
   FOREIGN KEY (SHOP) REFERENCES SHOP(ID),
   FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ID),
   FOREIGN KEY (REPORTS_TO) REFERENCES EMP(ID),
   CHECK (WORKLOAD BETWEEN 0.0 AND 1.0)
);

CREATE TABLE SHOP (
   ID INT PRIMARY KEY,
   NAME VARCHAR(100),
   ADDRESS INT,
   MANAGER INT,
   FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ID),
   FOREIGN KEY (MANAGER) REFERENCES EMP(ID)
);
