
DROP TABLE IF EXISTS DAMAGE CASCADE;
DROP TABLE IF EXISTS RENTAL CASCADE;
DROP TABLE IF EXISTS BIKE CASCADE;
DROP TABLE IF EXISTS BIKE_TYPE CASCADE;
DROP TABLE IF EXISTS SHOP CASCADE;
DROP TABLE IF EXISTS CUSTOMER CASCADE;
DROP TABLE IF EXISTS EMP CASCADE;
DROP TABLE IF EXISTS ADDRESS CASCADE;
