--deactivate statement for non-existing tables
DROP TABLE DAMAGE CASCADE CONSTRAINTS;
DROP TABLE RENTAL CASCADE CONSTRAINTS;
DROP TABLE BIKE CASCADE CONSTRAINTS;
DROP TABLE BIKE_TYPE CASCADE CONSTRAINTS;
DROP TABLE SHOP CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE EMP CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE;
